title: Courageous Lion Wood Apple Orchard 
description: > # this means to ignore newlines until "baseurl:"
    I write a lot of words, some of the structured ones show up here.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Saurya Velagapudi # add your name
author-img: saurya.jpg # add your photo
about-author: I used to write software at Google, did my own startup for a while. I sometimes write science fiction on <a href="//www.medium.com/@sauryasimha">Medium</a> and here. # add description
social-twitter: saurya # add your Twitter handle
social-facebook: saurya # add your Facebook handle
social-github: saurya # add your Github handle
social-linkedin: saurya-velagapudi-74a8a621 # add your Linkedin handle
social-email: saurya@gmail.com # add your Email address

# Disqus
discus-identifier: sauryas-blog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
